name: Cron Jobs
on:
  schedule:
    - cron: "0 0 * * 6"
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  tfscan:
    uses: synapsestudios/.github/.github/workflows/tf-scan.yml@master
