name: Pull Request Jobs
on:
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  terraform-format-test:
    uses: ./.github/workflows/terraform_format.yml
  terraform-docs:
    needs: [terraform-format-test]
    uses: ./.github/workflows/documentation.yml
  tfscan:
    uses: synapsestudios/.github/.github/workflows/tf-scan.yml@master
