name: Pull Request Jobs
on:
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"
permissions:
  actions: read
  contents: write
  pull-requests: write
  security-events: write
jobs:
  terraform-format-test:
    uses: ./.github/workflows/terraform_format.yml
  terraform-docs:
    needs: [terraform-format-test]
    uses: ./.github/workflows/tf-docs.yml
  tfscan:
    needs: [terraform-format-test, terraform-docs]
    uses: synapsestudios/.github/.github/workflows/tf-scan.yml@master
