name: tfsec-pr-commenter
on:
  workflow_call:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          tfsec_args: --soft-fail
          working_directory: "" # Workaround for PR https://github.com/aquasecurity/tfsec-pr-commenter-action/issues/90
          github_token: ${{ github.token }}
